# -*- coding: utf-8 -*-
"""B_Classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1szJPbU2fhHFYR8sXZj19IklqZYb1bw7S
"""

##### Please adjust the column headers as per our convention.

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('dataset_b7.csv', header = None, names = ['Label', 'Values'])
df.head()

# From the above histgrams, we can observe that if a value is less than 0.5, it belongs to bn class else it goes into bo class. (99% true cases)
def classify_b(value):
  if value < 0.5:
    return 'bn'
  else:
    return 'bo'

classify_b(0.5)

print(classify_b(0.8))

