# -*- coding: utf-8 -*-
"""Group_7_week_9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aY_kOYu3z6Es9I6q51ee4o5uaGNt3ZWW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Question (a)"""

df = pd.read_csv("dataset_o7.csv", header = None, names = ['Class', 'Feature1', 'Feature2', 'Feature3', 'Feature4', 'Feature5', 'Feature6', 'Feature7', 'Feature8'])
df.head(10)

"""Question (b)"""

classes = df['Class'].unique()
classes.sort()


"""Question (d)"""

#Yes, the grouping criteria has been implemented in part (f)


# Classify_O function

def classify_o(values):
    if values[0] > 1.5:
        if values[4] < 0.5:
            return 'o1'
        else:
            return 'o7'

    if 0.2 <= values[1] <= 0.7:
        return 'o4'

    if values[2] >= 0.5:
        return 'o0'

    if values[3] >= 0.5:
        if values[5] >= 0.5:
            return 'o6'
        else:
            return 'o8'

    if values[4] >= 0.5:
        if values[0] <= 1.5:
            if values[6] <= 0.5:
                return 'o2'
            else:
                return 'o3'

    if values[5] >= 0.5:
        if values[1] < 0.4:
            return 'o5'

    if values[6] > 0.5:
        if values[0] <= 1.5:
            if values[4] < 0.5:
                if values[5] < 0.5:
                    if values[1] >= 0.7:
                        return 'o9'
    else:
        return 'NA'

input_values = [2.025585, 0.005348, 0.021117, 0.031764, 0.054229, 0.033169, 0.019104, 0.085797]
result = classify_o(input_values)
print(result)


